# SPDX-FileCopyrightText: 2023 Filipe Laíns
#
# SPDX-License-Identifier: EUPL-1.2

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.10'

python:
  install:
    - method: pip
      path: .
      extra_requirements: [docs]
